- name: Compile neovim from source for RHEL
  block:
    - name: clone neovim
      git:
        dest: ~/opensource/neovim
        repo: https://github.com/neovim/neovim.git
        version: v0.6.1
    - name: compile neovim from source
      make:
        chdir: ~/opensource/neovim
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo
    - name: Install neovim
      become: yes
      make:
        chdir: ~/opensource/neovim
        target: install

  when: ansible_os_family == "RedHat"
