- name: Install neovim from package manager
  package:
    name: neovim
    state: present
  when: not neovim['compile_from_source']

- name: Compile neovim from source
  block:
    - name: clone neovim
      git:
        dest: ~/opensource/neovim
        repo: https://github.com/neovim/neovim.git
        version: "{{ neovim['version'] }}"
    - name: compile neovim from source
      make:
        chdir: ~/opensource/neovim
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo
    - name: Install neovim
      become: yes
      make:
        chdir: ~/opensource/neovim
        target: install
  when: neovim['compile_from_source']
