- name: Install packages
  become: "{{ python3['install_become'] }}"
  package:
    state: present
    name: "{{ python3['packages'] }}"

- name: Get pip3 executable
  shell: command -v pip3 || true
  register: pip3
  changed_when: false

- name: Install pip packages
  become: yes
  pip:
    executable: "{{ pip3.stdout }}"
    name:
      - neovim
      - cmake
      - jedi-language-server
      - pyright
      - autopep8
      - ansible
      - debugpy

