- name: Install rustup packages
  become: "{{ rust['install_become'] }}"
  package:
    name: "{{ rust['packages'] }}"

- name: Install rustup on Redhat
  shell: |
    curl --proto '=https' --tlsv1.2 -ysSf https://sh.rustup.rs | sh
  when: rust['download_rustup']

- name: Install dev tools
  shell: |
    rustup +nightly component add rust-analyzer-preview
    rustup component add rustfmt --toolchain nightly

