---

- name: homebrew
  block:
    - name: Check for brew
      stat:
        path: /opt/homebrew/bin/brew
      register: brew_exists

    - name: Install brew if not present
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_exists.stat.exists

    - name: Update brew if present
      homebrew:
        update_homebrew: true
      when: brew_exists.stat.exists
  when: ansible_os_family == "Darwin"

- name: Install repos
  become: "{{ packages['install_become'] }}"
  package:
    name: "{{ packages['repos'] }}"
  when: packages['repos'] != "" and packages['repos'] != [] and package['repos'] != None

- name: Install packages
  become: "{{ packages['install_become'] }}"
  package:
    name: "{{ packages['packages'] }}"
