---


- hosts: dotfiles
  roles:
    - packages
    - dotfiles
    - { name: python3, ignore_errors: yes }
    - { name: lua, ignore_errors: yes }
    - { name: ocaml, ignore_errors: yes }
    - { name: rust, ignore_errors: yes }
