---

- hosts: dotfiles
  tasks:
    - add_host:
        groups: '{{ ansible_os_family }},{{ ansible_distribution }}'
        name: '{{ inventory_hostname }}'
      changed_when: false
      name: Add hosts to their os family groups
    - name: Print system info
      debug:
        msg: '{{ ansible_os_family }} : {{ ansible_distribution }}'
- hosts: dotfiles
  roles:
    - packages
    - dotfiles
    - fonts
    - ignore_errors: true
      name: python3
    - ignore_errors: true
      name: lua
    - ignore_errors: true
      name: ocaml
    - ignore_errors: true
      name: rust
    - ignore_errors: true
      name: neovim
