---

- hosts: dotfiles
  tasks:
    - name: Add hosts to their os family groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "{{ ansible_os_family }},{{ ansible_distribution }}"
      changed_when: false

    - debug:
        msg: "{{ ansible_distribution }}"

- hosts: dotfiles
  roles:
    - packages
    - dotfiles
    - { name: python3, ignore_errors: yes }
    - { name: lua, ignore_errors: yes }
    - { name: ocaml, ignore_errors: yes }
    - { name: rust, ignore_errors: yes }
    - { name: neovim, ignore_errors: yes }
