- name: Install packages
  become: "{{ lua['install_become'] }}"
  package:
    state: present
    name: "{{ lua['packages'] }}"

# TODO -- Build lua-language-server for RHEL

- name: Get whether or not lua-format exists
  shell: command -v lua-format || true
  register: lua_format
  changed_when: lua_format.stdout == ""

- name: Install luaformatter packages
  become: yes
  shell: |
    luarocks install --server=https://luarocks.org/dev luaformatter
  when: lua_format.stdout == ""

